---
- name: install packages
  with_items: "{{ letsencrypt_packages }}"
  package:
    name: "{{ item.name }}"

- name: register letsencrypt
  command: acme.sh --register-account -m "{{ letsencrypt_account }}" --home /root/.acme.sh
  args:
    creates: /root/.acme.sh

- name: create dnsapi link
  file:
    src: /usr/local/share/examples/acme.sh/dnsapi
    dest: /root/.acme.sh/dnsapi
    state: link
    force: yes

- name: create certs directory
  file:
    path: /etc/certs
    state: directory

- name: install cron job
  cron:
    name: "acme.sh"
    special_time: daily
    job: '/usr/local/sbin/acme.sh --cron --home "/root/.acme.sh"'
